
# source common.sh

# roboshop_app_password=$1

# if [ -z "${roboshop_app_password}" ]; then  ## roboshop123
#   echo -e "\e[31mNeed Mysql Root Password\e[0m"
#   exit 1
# fi


# print_head "Setup Erlang repos"
# curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash &>>{log_file}
# status_check $?

# print_head "Setup Rabbitmq repos"
# curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>{log_file}
# status_check $?

# print_head "installing Rabbitmq"
# dnf install rabbitmq-server -y  &>>{log_file}
# status_check $?

# print_head "Enable Rabbitmq"
# systemctl enable rabbitmq-server  &>>{log_file}
# status_check $?

# print_head "start Rabbitmq service"
# systemctl start rabbitmq-server &>>{log_file}
# status_check $?

# print_head "Add Application user"
# rabbitmqctl list_users | grep roboshop  &>>{log_file}
# if [ $? -ne 0 ]; then
#   rabbitmqctl add_user roboshop ${roboshop_app_password} &>>{log_file}
# fi
# status_check $?

# print_head "configuration permmistion for Appuser"
# rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>{log_file}
# status_check $?







- name: Print rabbitmq
  debug:
    msg: rabbitmq

- name: Setup Erlang Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: install Rabbitmq repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
 
- name: installing Erlang & Rabbitmq
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    state: installed


- name: Enable and start the rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes


- name:  Add application User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

