
- name: applaction user
  ansible.builtin.user:
     name: roboshop

- name: remove old content
  ansible.builtin.file:
    path: /app 
    state: absent

- name: create App Directory 
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract the {{ component }} content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes



   