


- name: configure the nodejs repo
  ansible.builtin.shell: curl -sL https:///rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: app_prereq_setup
  ansible.builtin.import_tasks:
    file: app_prereq_setup.yml

- name: Installing nodejs dependencies.
  community.general.npm:
    path: /app

- name: schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: schema_setup is defined

- name: systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

